### ISSUE TITLE
Analysis.ApiSL.ApiSlRuntimeErrors.UnsafeCode

### ISSUE THREAD

**Issue by ethanvaughn** [hpsa/hp-application-automation-tools-plugin#139]
Receiving the following error when running the plugin. The scenario completes, but the analysis fails. I'm using version 4.5.0 of the plugin. 

```
starting analysis launcher
creating analysis COM object
creating analysis session
Loader Manager initialization failed.
   at Analysis.ApiSL.ApiSlRuntimeErrors.Throw(Int32 aErrorCode, ApiException aException)
   at Analysis.ApiSL.ApiSlRuntimeErrors.UnsafeCode(UnsafeCodeHandlerBool aHandler, Int32 aLraErrorCode)
   at Analysis.Api.Session.CreateWithTemplateFile(String aSessionName, String aResultFileName, String     aTemplateFileName)
   at LRAnalysisLauncher.Program.Main(String[] args)
time passed: 00::00:00:01
Error: Error during Analysis run. See output console for details
analysis report generator finished
Error(s) summary: 
0 ignored , 0 errors
```

This same Jenkins job worked on a different LR controller host (as a Jenkins slave), but is failing on this host. I get the same error when running at the command prompt.

**Comment by YafimK** [comment]
Hi please open up this issue on our plugin Jira
https://issues.jenkins-ci.org/issues/?jql=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27hp-application-automation-tools-plugin%27

**Comment by ethanvaughn** [comment]
BTW, the LRA and LRR dirs get created, but the HTML does not. Here are the contents: 

    9eb25c\
        LRA\
            LRA.mdb
        LRR\
            log\
                validate_10.log
            sum_data\
                graph_0-5.dat
                sum_dat.ini
    9eb25c\
        LRA\
            LRA.mdb
        LRR\
            log\
                validate_10.log
            sum_data\
                graph_0-5.dat
                sum_dat.ini
            _t_rep.eve                   1 KB
            api1_script_1.cfg         3 KB  <--- "api1_script" is the name of my LR script
            api1_script_1.cfg.bak   3 KB
            api1_script_1.usp        4 KB
            collate.txt                    1 KB
            collateLog.txt               1 KB
            crossvusertrans_error_report.txt  0 KB
            ei669vwin_1.eve.gzl      4 KB  <--- "ei669vwin" is the name of the load generator host
            ei669vwin.map             4 KB
            LRR.lrr                          1 KB
            offline.dat                     0 KB
            output.mdb                 528 KB
            read_eve.log                1 KB
            remote_results.txt        1 KB
            SLAConfiguration.xml   4 KB

**Comment by YafimK** [comment]
moved to JIRA
