### ISSUE TITLE
What's the license

### ISSUE THREAD

**Issue by s1pande** [hpsa/hp-application-automation-tools-plugin#14]
Couldn't find a way to identify the license associated. It doesn't show up after installing in jenkins (Tried http://jenkinsurl/about) that shows the plugins installed with their licenses.

**Comment by mrmann** [comment]
Hi,

The license is MIT license (http://opensource.org/licenses/MIT)


Avishai Moshka
R&D
HP Software
LoadRunner

avishai.moshka@hp.com
<mailto:avishai.moshka@hp.com>M +972-53-6660741
T +972-3-5397214
Hewlett-Packard Company
[HP]<http://www.hp.com/>

**Comment by s1pande** [comment]
Thank you for the info. Appreciate it.
