### ISSUE TITLE
subdir LRR is missing when results path is passed to Analysis launcher from HpToolsLauncher

### ISSUE THREAD

**Issue by ogarling** [hpsa/hp-application-automation-tools-plugin#20]
Hi,

When invoking LoadRunner 12.02 the plugin (version 3.08_Snapshot) issues a wrong LRR argument.
Please see the log below:
The actual LRR dir should be: "C:\dev\tools\Jenkins\workspace\TruClient_Jenkins2\549b73\LRR\LRR.lrr".
For the other arguments (LRA & HTML) the directory paths are valid.

Thanks for all your work by the way!
I hope you can fix this.

With kindest regards,
Okke

===================================
Analyzing results...
closing Controller
Controller closed
calling analysis report generator
executing Analysis launcher with arguments : "C:\dev\tools\Jenkins\workspace\TruClient_Jenkins2\549b73\LRR.lrr" "C:\dev\tools\Jenkins\workspace\TruClient_Jenkins2\549b73\LRA\LRA.lra" "C:\dev\tools\Jenkins\workspace\TruClient_Jenkins2\549b73\HTML\HTML.html"
time for analysis: 00::03:00:00
starting analysis launcher
creating analysis COM object
creating analysis session
Result loading failed. Log has been saved to: "C:\Windows\TEMP\Ana_548362814.log"
   at Analysis.ApiSL.ApiSlRuntimeErrors.Throw(Int32 aErrorCode, ApiException aException)
   at Analysis.ApiSL.ApiSlRuntimeErrors.UnsafeCode(UnsafeCodeHandlerBool aHandler, Int32 aLraErrorCode)
   at Analysis.Api.Session.CreateWithTemplateFile(String aSessionName, String aResultFileName, String aTemplateFileName)
   at LRAnalysisLauncher.Program.Main(String[] args)
time passed: 00::00:00:01
Error: Error during Analysis run. See output console for details
analysis report generator finished
Error(s) summary: 
0 ignored , 0 errors

Test PASSED
Test result: Passed
05/03/2015 14:37:39 Test complete: C:\dev\tools\LR4Jenkins\scenarios\JenkinsTC.lrs

**Comment by ogarling** [comment]
In the code it seems correct:

`       private void generateAnalysisReport(TestRunResults runDesc)`
`        {`
`            string lrrLocation = Path.Combine(runDesc.ReportLocation, LRR_FOLDER, LRR_FOLDER + ".lrr");`

Somebody an idea why the subdir LRR is left out when passing the arguments to Analysis launcher? (see log file above)

**Comment by mrmann** [comment]
hi,

the problem seems to be that Controller (for some unknown reason) can't write to the defined LRR folder so it generate a different folder for the results.

i will commit the fix in a few moments

**Comment by mrmann** [comment]
fix committed to 3.0.8_snapshot
1a049fb2dc0cd645367f06eb50aff0ae130bde65

**Comment by ogarling** [comment]
Unfortunately the fix was not the solution to my issue.
The solution for me is a modification to line 428 in \HpToolsLauncher\TestRunners\PerformanceTestRunner.cs:
`string lrrLocation = _controller_result_dir + "\\LRR.lrr";`

Very strange that the setting of `lraLocation` and `htmlLocation` DO work the old way. I see no diffence in the use of the `Path.Combine` function. But as being said: it works now with my fix.

**Comment by ogarling** [comment]
Hi Avishai,

Thanks for your effort.

Unfortunately the fix was not the solution to my issue.
The solution for me is a modification to line 428 in
\HpToolsLauncher\TestRunners\PerformanceTestRunner.cs:
string lrrLocation = _controller_result_dir + "\\LRR.lrr";

Very strange that the setting of lraLocation and htmlLocation DO work the
old way. I see no diffence in the use of the Path.Combine function. But as
being said: it works now with my fix. I was able to compile it myself.


Kind regards,

Okke



2015-03-11 12:56 GMT+01:00 Avishai Moshka <notifications@github.com>:
