### ISSUE TITLE
ALM 11.52 - Jenkins Plugin does not work for Windows 7, 64bit OS

### ISSUE THREAD

**Issue by thusai000** [hpsa/hp-application-automation-tools-plugin#22]
Open issues: https://issues.jenkins-ci.org/browse/JENKINS-19374
https://issues.jenkins-ci.org/browse/JENKINS-23303

$ cmd /c call C:\Windows\TEMP\hudson2323780814887389999.bat
C:\Jenkins\workspace\xxx>HpToolsLauncher.exe -paramfile props.txt
...
Could not create scheduler, please verify ALM client installation on run machine by downloading and in installing the add-in form: https://almxxx.saas.hp.com/qcbin/TDConnectivity_index.html
Build step 'Execute Windows batch command' marked build as failure

**Comment by SergeySafronov** [comment]
Hi thusai000,
This Solution should help:
Need to register ALM client in common mode on a machine where need to execute tests:
http://<ALM_address>:8080/qcbin/start_a.jsp?common=true

**Comment by sergey-oplavin** [comment]
Hi Sergey, this solution still does not work if Jenkins (or slave where plugin is executed) is running as a service.

**Comment by SergeySafronov** [comment]
> Hi Sergey, this solution still does not work if Jenkins (or slave where plugin is executed) is running as a service.
Hi Sergey,
On the Jenkins slave machine, make sure that the Jenkins Slave service is not logged in with the Local System account. To function properly, it should log in with an account the has administrator privileges.
You can find more info about it on a plugin wiki page at the buttom of the page:
https://wiki.jenkins-ci.org/display/JENKINS/HP+Application+Automation+Tools

**Comment by sergey-oplavin** [comment]
Hi Sergey,
Thanks for the answer, we have already figured that out :)
But thanks anyway
